# Generated by Django 3.2.7 on 2021-09-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=40)),
                ('message_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('chat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.channels')),
            ],
        ),
    ]
