# Generated by Django 3.2.7 on 2021-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
